# ---------------------------------------------------------------------
# Used when loading the docs within the context of the website. LOCAL.
# ---------------------------------------------------------------------

# site settings
title: Form Tools Documentation
email: ben.keen@gmail.com
description: "Documentation and tutorials for all things Form Tools."
baseurl: "http://localhost:4000/docs.formtools.org"
url: "http://docs.formtools.org"
resourceurl: "http://localhost:4000/formtools.org"
ft_url: "http://localhost:4000/formtools.org"
accounts_url: "http://localhost:4000/accounts.formtools.org"
docs_url: "http://localhost:4000/docs.formtools.org"
modules_url: "http://localhost:4000/modules.formtools.org"
themes_url: "http://localhost:4000/themes.formtools.org"
translations_url: "http://localhost:4000/translations.formtools.org"
forums_url: "http://localhost:4000/themes.formtools.org"

# build settings
markdown: kramdown
permalink: pretty
showWrapper: true
